/** * Copyright (c) 2009-2015 Social Vision GmbH. All rights reserved. */
package com.ni3.ag.navigator.client.controller;

public interface Ni3ItemListener{
	public static final int MSG_NodeShowToolTip = 3;
	public static final int MSG_EdgeShowToolTip = 4;
	public static final int MSG_FilterChanged = 5;
	public static final int MSG_FilterTreeChanged = 6;
	public static final int MSG_SubgraphChanged = 7;
	public static final int MSG_PreFilterChanged = 8;
	public static final int MSG_PreFilterTreeChanged = 9;
	public static final int MSG_SchemaChanged = 10;
	public static final int MSG_SubgraphBeforeChange = 11;
	public static final int MSG_BeforeSearch = 12;
	public static final int MSG_NewSubgraph = 13;
	public static final int MSG_ClearSubgraph = 14;
	public static final int MSG_GraphDirty = 15;
	public static final int MSG_ClearSearchResult = 16;
	public static final int MSG_LoadFavorite = 21;
	public static final int MSG_ClearFavorite = 22;
	public static final int MSG_SubgraphObjectsRemoved = 24;
	public static final int MSG_ChartFilterChanged = 25;
	public static final int MSG_MetaphorSetChanged = 26;
	public static final int MSG_ThematicDataChanged = 27;
	public static final int MSG_ChartAFChanged = 28;
	public static final int MSG_ChartTOChanged = 29;
	public static final int MSG_ChartVSChanged = 30;
	public static final int MSG_OverlayDataChanged = 31;
	public static final int MSG_DynamicAttributeAdded = 32;
	public static final int MSG_DynamicAttributesCleared = 33;
	public static final int MSG_DBChanged = 34;
	public static final int MSG_QueryNumberChanged = 35;
	public static final int MSG_GraphPanelSettingsChanged = 36;
	public static final int MSG_FilterNew = 38;
	public static final int MSG_PrefilterNew = 39;
	public static final int MSG_EdgeCountChanged = 40;
	public static final int MSG_NodeCountChanged = 41;
	public static final int MSG_StatusChanged = 42;
	public static final int MSG_NodeRemoved = 43;
	public static final int MSG_DataSetChanged = 44;
	public static final int MSG_FavoriteLoaded = 45;
	public static final int MSG_MapSettingsChanged = 46;
	public static final int MSG_MapChanged = 47;
	public static final int MSG_ShowOnlyDisplayedNodesInMatrixChanged = 48;
	public static final int MSG_ShowNumericMetaphorsChanged = 49;
	public static final int MSG_SearchNewChanged = 50;
	public static final int MSG_MatrixPointedNodeChanged = 51;
	public static final int MSG_NodeExpressCreateChanged = 52;
	public static final int MSG_EdgeExpressCreateChanged = 53;
	public static final int MSG_CreateNode = 54;
	public static final int MSG_CreateEdge = 55;
	public static final int MSG_CommandPanelSettingsChanged = 56;
	public static final int MSG_GraphPointedNodeChanged = 58;
	public static final int MSG_MapPointedNodeChanged = 59;
	public static final int MSG_MapPositionChanged = 61;
	public static final int MSG_InFocusEdgesChanged = 62;
	public static final int MSG_NodeSelectionChanged = 63;
	public static final int MSG_TopicModeChanged = 64;
	public static final int MSG_GeoLegendDataChanged = 65;
	public static final int MSG_ThematicMapsChanged = 66;
	public static final int MSG_GraphLayoutManagerChanged = 67;
	public static final int MSG_ThematicMapChanged = 68;
	public static final int MSG_OverlaysChanged = 69;
	public static final int MSG_ChartTypeChanged = 70;
	public static final int MSG_ChartChanged = 71;
	public static final int MSG_ChartLegendVisibilityChanged = 72;
	public static final int MSG_MatrixSortChanged = 74;
	public static final int MSG_NodeIconChanged = 75;
	public static final int MSG_Reload = 76;
	public static final int MSG_RecalculateStatistics = 77;
	public static final int MSG_ShowContractedEdgeCounterChanged = 78;
	public static final int MSG_FavoritesUpdated = 79;
	public static final int MSG_PolygonModelChanged = 80;
	public static final int MSG_PolygonColorChanged = 81;
	public static final int MSG_SnaChartChanged = 82;

	public static final int SRC_Unknown = -1;
	public static final int SRC_Doc = 0;
	public static final int SRC_Graph = 1;
	public static final int SRC_LegendFrame = 2;
	public static final int SRC_FiltersPanel = 3;
	public static final int SRC_MetaphorLegendFrame = 4;
	public static final int SRC_MainPanel = 5;
	public static final int SRC_FilterTree = 6;
	public static final int SRC_PreFilterTree = 7;
	public static final int SRC_FavoritesMenu = 8;
	public static final int SRC_FavoritesManager = 9;
	public static final int SRC_GIS = 10;
	public static final int SRC_ItemsPanel = 11;
	public static final int SRC_Other = 12;
	public static final int SRC_LegendFilterSlider = 14;
	public static final int SRC_SNA = 15;
	public static final int SRC_OtherGUIComponents = 16;
	public static final int SRC_ChartLegendView = 19;

	public int getListenerType();

	public void event(int eventCode, int sourceID, Object source, Object param);
}
